export const events = [
  {
    id: 1,
    image:"/images/event1.png",
    title: "React Summit 2025",
    slug: "react-summit-2025",
    category: "Conference",
    location: "Amsterdam, Netherlands",
    venue: "DeLaMar Theater",
    date: "2025-06-12",
    endDate: "2025-06-13",
    time: "09:00",
    endTime: "18:00",
    description: "The biggest React conference in Europe returns with world-class speakers.",
    price: "€649 – €999",
    isFree: false,
    featured: true,
    ticketsUrl: "https://reactsummit.com",
  },
  {
      id: 2,
      image:"/images/event2.png",
      title: "Next.js Conf 2025",
      slug: "nextjs-conf-2025",
      category: "Conference",
      location: "San Francisco, CA, USA",
      venue: "Yerba Buena Center for the Arts",
      date: "2025-10-28",
      time: "08:30",
      endTime: "17:30",
      description: "Official Next.js conference by Vercel featuring the latest in React and web performance.",
      price: "Free (Virtual) / $799 (In-Person)",
    isFree: false,
    featured: true,
    ticketsUrl: "https://nextjs.org/conf",
},
{
    id: 3,
    image:"/images/event3.png",
    title: "TypeScript Congress 2025",
    slug: "typescript-congress-2025",
    category: "Conference",
    location: "Berlin, Germany",
    venue: "bcc Berlin Congress Center",
    date: "2025-09-18",
    time: "10:00",
    description: "Deep dive into advanced TypeScript patterns, tooling, and large-scale applications.",
    price: "€399 Early Bird",
    isFree: false,
    featured: false,
},
{
    id: 4,
    image:"/images/event4.png",
    title: "Tailwind Connect 2026",
    slug: "tailwind-connect-2026",
    category: "Conference",
    location: "Salt Lake City, UT, USA",
    venue: "The Grand America Hotel",
    date: "2026-02-20",
    time: "09:00",
    description: "The official conference for Tailwind CSS enthusiasts and design engineers.",
    price: "TBA",
    isFree: false,
    featured: true,
},
{
    id: 5,
    image:"/images/event5.png",
    title: "JavaScript Lovers Monthly Meetup #47",
    slug: "js-lovers-meetup-december-2025",
    category: "Meetup",
    location: "Lagos, Nigeria",
    venue: "Co-Creation Hub (CcHUB)",
    date: "2025-12-18",
    time: "18:00",
    endTime: "21:00",
    description: "Lightning talks, networking, and pizza. This month: State Management in 2026.",
    price: "Free",
    isFree: true,
    featured: false,
},
  {
      id: 6,
      image:"/images/event6.png",
      title: "Frontend Nation 2025",
      slug: "frontend-nation-2025",
    category: "Conference",
    location: "Online",
    venue: "Virtual Event",
    date: "2025-06-03",
    endDate: "2025-06-06",
    time: "14:00 UTC",
    description: "4 days of talks, workshops, and panels — 100% online and accessible worldwide.",
    price: "Free – $199",
    isFree: false,
    featured: false,
},

];